/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#faf9fe',
        'surface-dim': '#dad9df',
        'surface-bright': '#faf9fe',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f8',
        'surface-container': '#eeedf3',
        'surface-container-high': '#e9e7ed',
        'surface-container-highest': '#e3e2e7',
        'on-surface': '#1a1b1f',
        'on-surface-variant': '#414755',
        'inverse-surface': '#2f3034',
        'inverse-on-surface': '#f1f0f5',
        outline: '#717786',
        'outline-variant': '#c1c6d7',
        'surface-tint': '#005bc1',
        primary: '#0058bc',
        'on-primary': '#ffffff',
        'primary-container': '#0070eb',
        'on-primary-container': '#fefcff',
        'inverse-primary': '#adc6ff',
        secondary: '#006e28',
        'on-secondary': '#ffffff',
        'secondary-container': '#6ffb85',
        'on-secondary-container': '#00732a',
        tertiary: '#894d00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ac6300',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a41',
        'on-primary-fixed-variant': '#004493',
        'secondary-fixed': '#72fe88',
        'secondary-fixed-dim': '#53e16f',
        'on-secondary-fixed': '#002107',
        'on-secondary-fixed-variant': '#00531c',
        'tertiary-fixed': '#ffdcbf',
        'tertiary-fixed-dim': '#ffb874',
        'on-tertiary-fixed': '#2d1600',
        'on-tertiary-fixed-variant': '#6a3b00',
        background: '#faf9fe',
        'on-background': '#1a1b1f',
        'surface-variant': '#e3e2e7',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['34px', { lineHeight: '41px', letterSpacing: '-0.4px', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.4px', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.4px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '22px', letterSpacing: '-0.4px', fontWeight: '400' }],
        'body-sm': ['15px', { lineHeight: '20px', letterSpacing: '-0.2px', fontWeight: '400' }],
        'label-caps': ['13px', { lineHeight: '18px', letterSpacing: '0.1px', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      spacing: {
        'margin-mobile': '16px',
        'gutter': '12px',
        'card-padding': '16px',
        'stack-gap': '20px',
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '12px', // overridden to 12px based on Button instructions (rounded-lg = 12px)
        'xl': '16px', // overridden to 16px based on Card instructions (rounded-xl = 16px)
        'full': '9999px',
      },
      boxShadow: {
        'card': '0px 2px 8px rgba(0, 0, 0, 0.04)',
        'modal': '0px 4px 16px rgba(0, 0, 0, 0.12)',
      }
    },
  },
  plugins: [],
}
